### ISSUE TITLE
Packages file committed 

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#38]
You should have excluded the packages from your PR.
You will need to remove them from git before you ignore them now, or they will be here forever.
Generally we would be including package references in a csproj or package lock file but ignore anything in the bin, build, and debug type folders. That is all generated when the solution builds

**Comment by HexCrispin** [comment]
Sorted in this: https://github.com/TheInferos/DnD-Monster-Builder/commit/1792ad10c03702b6c332e6f85dd7a238964d02fe

Delete will be done shortly with merge
