### ISSUE TITLE
Delete save endpoint on the bestiary controller

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#39]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/Controllers/BeastiaryController.cs#L20

Saving changes should happen automatically and be handled by the bestiary repository.
It is fair enough to batch up changes to avoid lots of file writes. Or handle concurrency issues but there should not be a public method on the repository called save. It may be acceptable to have a flush method on the repo so that it can be forever to save early by internal services as well as automatically when it feels like it's necessary. Kinda overkill, but if you are going this way consider looking at the IDisposable interface.

**Comment by HexCrispin** [comment]
Deleted on this commit: https://github.com/TheInferos/DnD-Monster-Builder/commit/9b0b4598e915ed0a1c50a7d865b5663280d0430d
