### ISSUE TITLE
Access Modifiers on properties 

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#40]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/Controllers/MonsterController.cs#L12

It is a good idea to always mark the level of protection on properties, even though they will gain a default level.
Also consider if the readonly modifier can also be used. In this case it could be since the services are only set during construction. If you prefer there is also an init modifier

**Comment by HexCrispin** [comment]
This was fixed as part of reevaluating protection levels in the Controllers and Services so marking as done
