### ISSUE TITLE
Armour Constructor Parameter missmatch

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#42]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/Models/Armour.cs#L87C8-L87C8

The properties are declared as nullable but they cannot be passes as nulls in the constructor. Either mark as not null or allow nullables to be passes in the constructor

**Comment by HexCrispin** [comment]
Fixed on: https://github.com/TheInferos/DnD-Monster-Builder/tree/f89dc537d2073b5be30bcaa7e70d74af3cf3925c
