### ISSUE TITLE
Monster constructor mismatched types

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#43]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/Models/Monster.cs#L24

The constructor accepts floats but needs ints.
Cast failure is not handled

**Comment by HexCrispin** [comment]
Updated on this with TODO left to cover full funtionality: https://github.com/TheInferos/DnD-Monster-Builder/commit/bc77a1e3848a73eb3498e941ec496b87c9cb9214
