### ISSUE TITLE
MonsterActions can be created without the expected fields

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#44]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/Models/MonsterAction.cs#L8

Consider marking some or all of the fields as required so you know all the necessary data is set. Mark the rest as nullable so it is clear they may not have a value.
This will give you compile time warnings if you try to access a field that may be null without checking

**Comment by HexCrispin** [comment]
This commit forces default values if there are none, I don't think  required is what I'm looking for. https://github.com/TheInferos/DnD-Monster-Builder/pull/61
