### ISSUE TITLE
Weapons Repo contains two unsynced collections of weapons

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#46]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/Repositories/IWeaponRepository.cs#L7

There are two collections that appear identical and are not in sync. I assume this is a mistake but if not they need more obvious names so that the correct one is used. Consider adding a summary comment if you cannot create good names.

Also see the issue with exposing the collections directly

**Comment by HexCrispin** [comment]
This was not workingas intended. One is supposed to be privately used and one is the public interface fix applied here: https://github.com/TheInferos/DnD-Monster-Builder/commit/f7d0be5b881f5278f18f6a0170f20e61288c6ec5
