### ISSUE TITLE
Public save and load methods

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#47]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/Services/BeastiaryService.cs#L21

Data loading and saving should not be a concern for the consumer of these services
Just do it in the constructor or even fancier look up lazy loading. It. Will be a fun way to show off and save memory
You can also investigate IDisposable for writing to file if you don't want to do that every time a change is made

**Comment by HexCrispin** [comment]
Issue removed. will look into IDispossables
https://github.com/TheInferos/DnD-Monster-Builder/commit/58425673a53146ff22c0e7937f58b798c26c4625
