### ISSUE TITLE
Separate JS from html

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#48]
https://github.com/TheInferos/DnD-Monster-Builder/blob/d1462ceb6064c56f7c35ba1e4bfdc6e4d504b252/index.html#L136

You will get nicer syntax highlighting if you pull the scripts into a separate file. Though I expect your js is better than mine so maybe you are fine without it.
If the file gets a lot longer do it anyway to help break things into logical groups

**Comment by HexCrispin** [comment]
Fixed as part of this commit: https://github.com/TheInferos/DnD-Monster-Builder/pull/63
