### ISSUE TITLE
Constructor not setting up default value

### ISSUE THREAD

**Issue by elispb** [TheInferos/DnD-Monster-Builder#53]
https://github.com/TheInferos/DnD-Monster-Builder/blob/4db139f1acee0d9191cc8958cfb2d2ccb7e1b455/Models/ActionEffect.cs#L22-L26

I think you want to swap those
```
public ActionEffect(string description) 
 { 
     Description = description;   
 } 
```
or did you want to do this
```
public ActionEffect(string description) 
 { 
     this.description = description;   
 } 
```
if so maybe rename the parameter so it is clearly distinct

**Comment by HexCrispin** [comment]
Nice spot fixed in https://github.com/TheInferos/DnD-Monster-Builder/commit/6bbbf73c920c970f2642b8cbe756463c3c08704b
